baseURL = 'https://stefanogabryel.net/'
languageCode = 'en-us'
title = 'Stefano Gabryel | Hiking and Photography in Tuscany'
theme = "alpins"

[pagination]
  pagerSize = 500

[permalinks]
  posts = "/blog/:slug/"


[params]
    # footer infos
    piva = "IT02089670471"
    iban = "IT17B3609201600524148650894"

    # contacts
    instagramLink = "https://www.instagram.com/stefano.gabryel/"
    whatsappLink = "https://wa.me/message/T4667RVAVPEJB1"
    email = "stefano.gabryel@gmail.com"
    phone = "+39 351 366 3017"


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 3